### ISSUE TITLE
Adding Facebook prophet

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#10]
Facebook Prophet is a strong time series forecasting tool that may be used for derivative hedging. It is an open-source program created by Facebook that forecasts time series data using a decomposable additive model. This model considers trends, seasonality, and holidays, making it especially useful for data with numerous seasonalities.

**Comment by chiragtyagi2003** [comment]
Hi Akshat, could you elaborate a little, I would like to work on it.

**Comment by Akshat111111** [comment]
I firstly suggest you to please refer to [https://www.kaggle.com/code/paramarthasengupta/microsoft-stocks-price-prediction](url)
I am also working on similar type of project wth hedge funds.Kindly ask if you need more clarification.

**Comment by Akshat111111** [comment]
Hey have you done anything on this issue??

**Comment by Akshat111111** [comment]
yeah, I am still open for it.Please feel free to ask anything related to it.

**Comment by chiragtyagi2003** [comment]
Okay, I will update you soon.

**Comment by tejasvinigoel** [comment]
Could you please assign this to me, thanks

**Comment by diptarup794** [comment]
@Akshat111111  I have made a pull request . Kindly review it allow it to merge . Thank you

**Comment by Akshat111111** [comment]
Kindly do the task so that I will merge it

**Comment by tejasvinigoel** [comment]
Where can I find the dataset for the task

**Comment by Akshat111111** [comment]
You can use any financial APIs or select dataset from kaggle.If you are using kaggle, dont forget to give references.

**Comment by diptarup794** [comment]
@Akshat111111  Kindly evaluate the changes made allow it to merge . Pls leave a feedback in case you feel any changes are required .

**Comment by tejasvinigoel** [comment]
ive made a pull request, kindly check
