### ISSUE TITLE
Adding a thanking workflow

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#101]
After success of the PR there should be a message of Thankyou for contributing to this repository.

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Akshat111111 I would like to work on this as part of GSSOC'24. Please assign this to me.

**Comment by A-b-i-r-a-m-i-G-S** [comment]
Also, please note that the labels should be gssoc and level3. Only then the contributions will be counted towards the leaderboard.
