### ISSUE TITLE
Adding a video in the readme

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#102]
The video will make the readme more user friendly and interactive. It will use animation to discuss the interrelation of financial market and other fields for the hedging and the future 2050.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , Please assign this task to me.

**Comment by JagjeetChauhan** [comment]
Hey @Akshat111111 can you please assign this task under gssoc'24?

**Comment by TohitCU** [comment]
@Akshat111111 we've to create animation for that ? please elaborate !

**Comment by Akshat111111** [comment]
> @Akshat111111 we've to create animation for that ? please elaborate !

yes animation.you are free to use any AI tool.Dont forget to give reference.

**Comment by TohitCU** [comment]
@Akshat111111  okay thanks will do !

**Comment by Akshat111111** [comment]
sure, I have assigned you too.
