### ISSUE TITLE
hey I have used ANN for Netflix Feedback Flash: Daily Updates

### ISSUE THREAD

**Issue by PRIYANSHU2026** [Akshat111111/Hedging-of-Financial-Derivatives#103]
The Netflix Reviews dataset contains information about user reviews submitted on the Google Play Store. It includes details such as the review ID, username, review content, review score, thumbs-up count, review creation version, review timestamp, and app version. This report aims to provide insights and analysis based on the dataset.

by using Dataset I have trained the model getting good prediction result from data set

**Comment by Akshat111111** [comment]
Kindly create a folder inside NYSE with name netflix analysis and put it there.

**Comment by Akshat111111** [comment]
Dont forget to give references as well as Netflix stock analysis inside it.
