### ISSUE TITLE
Add more visualisations to banglore_home_prices_final.ipynb to improve model performance.

### ISSUE THREAD

**Issue by FreeSpirit11** [Akshat111111/Hedging-of-Financial-Derivatives#124]
To further enrich the script's capabilities and improve its usefulness, I propose the addition of more visualizations to (Hedging-of-Financial-Derivatives/Hedging with Real Estate /banglore_home_prices_final.ipynb).

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I have raised this issue . Please assign it to me.

**Comment by merciajeno** [comment]
Hello Sir, even I want to work on this issue. Can you assign me?

**Comment by Akshat111111** [comment]
@FreeSpirit11 is working on it, so you can create a new issue as per the specification.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I created the pull request but It has some merge conflicts with the main branch. So if @merciajeno wants to resolve that issue. Please assign him too on this task.

**Comment by Akshat111111** [comment]
@merciajeno you want to resolve it ??

**Comment by merciajeno** [comment]
Yes Sir
