### ISSUE TITLE
Foreign Exchange (Forex) Rate Prediction

### ISSUE THREAD

**Issue by amishhaa** [Akshat111111/Hedging-of-Financial-Derivatives#140]
I am interested to create a model to forecast currency exchange rates between different countries based on factors like interest rates, inflation, trade balances, political stability. 
I request to be assigned this with appropriate GSSOC tags

**Comment by merciajeno** [comment]
Hello Sir, I have worked with ML models. Can you assign me ?

**Comment by Akshat111111** [comment]
> Hello Sir, I have worked with ML models. Can you assign me ?

Which model you will integrate ??

**Comment by anushka7220** [comment]
@Akshat111111 I am a GSSOC'24 contributor and i want to contribute in this issue
my approach is 
1. I will be using google colab to build this.
2. I will collect forex data from API-Alpha Vantage.
3. I will preprocess the data and buils LSTM model using tensorflow.
4. And finally evalution and loading will be done.

**Comment by Akshat111111** [comment]
> @Akshat111111 I am a GSSOC'24 contributor and i want to contribute in this issue my approach is
> 
> 1. I will be using google colab to build this.
> 2. I will collect forex data from API-Alpha Vantage.
> 3. I will preprocess the data and buils LSTM model using tensorflow.
> 4. And finally evalution and loading will be done.

sure,you can start working.

**Comment by anushka7220** [comment]
@Akshat111111 I ahve made a pull request of the desired model .
https://github.com/anushka7220/Hedging-of-Financial-Derivatives/pull/1

**Comment by Akshat111111** [comment]
you can refer to it- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by Akshat111111** [comment]
the pull request should be via github
