### ISSUE TITLE
As there already is code of conduct beside Readme you can either remove or update code of conduct in readme as it is showing page not found

### ISSUE THREAD

**Issue by TohitCU** [Akshat111111/Hedging-of-Financial-Derivatives#142]
![Screenshot 2024-05-17 231403](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/156745459/ce920fb6-9d51-4dbf-9b0c-72af27ac4d64)

**Comment by Akshat111111** [comment]
yes, you can start working

**Comment by TohitCU** [comment]
So i update it or remove it from readme ? @Akshat111111

**Comment by shubhamnakum** [comment]
@Akshat111111 i want to work on this issue please assign me. I will complete it ASAP.

**Comment by Akshat111111** [comment]
> @Akshat111111 i want to work on this issue please assign me. I will complete it ASAP.

@TohitCU is already working on it.you can create any new issue or work on the existing ones.

**Comment by TohitCU** [comment]
> So i update it or remove it from readme ? @Akshat111111

@Akshat111111 please confirm on this as your opinion matters !

**Comment by Akshat111111** [comment]
Update it
