### ISSUE TITLE
Enhancement Proposal: Prioritized Experience Replay and Dueling DQN Implementation in Reinforcement Learning for Market Hedging

### ISSUE THREAD

**Issue by Shubhanshu-356** [Akshat111111/Hedging-of-Financial-Derivatives#155]
Dear Akshat,

I hope this message finds you well. I would like to propose two significant enhancements to our trading agent project that I believe will significantly improve its performance and learning efficiency.
1.Prioritized Experience Replay:
Prioritizes informative transitions in the replay buffer based on their significance for learning.
Enhances training efficiency by sampling transitions with higher priorities more frequently, leading to faster convergence.

2.Dueling DQN:
Separates the estimation of state value and action advantages in the neural network architecture.
Improves learning efficiency by enabling the agent to learn the value of states and actions separately, resulting in more effective decision-making.
Both enhancements involve modifications to the codebase, including adjustments to the memory structure, replay methods, and model architecture. I believe that implementing these enhancements will significantly elevate the performance and robustness of our trading agent. Please give me this I work on it.
Thank You

**Comment by Akshat111111** [comment]
Thankyou for providing such a detailed description of your proposed approach.You can start working on it.

**Comment by Shubhanshu-356** [comment]
Thank you for considering I surely work on it and enhance it with the following proposal

**Comment by Shubhanshu-356** [comment]
Can you please give access as I can't be able to contribute. I have updated the code with the following enhancements which I have given but the thing I can't able to clone the repo and make the push and pull request please tell me what can I do. Can you please check from your side because i can't able to clone the repo in local machine. I have done the changes please reply.

**Comment by Akshat111111** [comment]
I have checked it, no other people are facing this issue.It is from your side only.You can try installing your github desktop again

**Comment by Shubhanshu-356** [comment]
Ok thanks I will do and make pull request as soon as possible

**Comment by Shubhanshu-356** [comment]
![Screenshot 2024-05-22 100650](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/115715087/fea234a4-4568-44bd-84e5-dab1956236f3)
This shows when I am cloning this repo to my local machine. Can you please help me in this I have updated the code the only thing I can't able to clone in my local machine. This I have tried from Github Desktop which you have told in your previous comment. Please help me in this.

**Comment by Akshat111111** [comment]
This is really strange.Let me find the solution

**Comment by Shubhanshu-356** [comment]
Can you please check I have pulled the request from github only because cloning is not done that's why I have directly done from github without cloning into the repo. I have pulled the request also.Please review my changes.

**Comment by Amarta113** [comment]
> Can you please check I have pulled the request from github only because cloning is not done that's why I have directly done from github without cloning into the repo. I have pulled the request also.Please review my changes.

@Shubhanshu-356 You can clone repo via vscode 
From the given options, select "Git Clone Repository". Here, you will need to enter the URL of the project
![image](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/134733248/92836d3d-f070-4e53-85ac-4948102c4e84)

**Comment by Shubhanshu-356** [comment]
Ok thanks for the help but i already done and open the pulled request also. Please review my changes @Akshat111111

**Comment by Shubhanshu-356** [comment]
Have you checked my pull request as it is not closed. Please check and review the changes

**Comment by Amarta113** [comment]
> Have you checked my pull request as it is not closed. Please check and review the changes

@Shubhanshu-356 He might be busy due to workload. I'm mentioning this because the mentor is also busy with his examinations. You can work on another issue in the meantime.

**Comment by Shubhanshu-356** [comment]
Ok no problem thanks for the info

**Comment by Akshat111111** [comment]
> > Have you checked my pull request as it is not closed. Please check and review the changes
> 
> @Shubhanshu-356 He might be busy due to workload. I'm mentioning this because the mentor is also busy with his examinations. You can work on another issue in the meantime.
> 

Hey, Thanks for it.You are absolutely correct. Apart from it I have GSOC tasks as well.

**Comment by Amarta113** [comment]
> > > Have you checked my pull request as it is not closed. Please check and review the changes
> > 
> > 
> > @Shubhanshu-356 He might be busy due to workload. I'm mentioning this because the mentor is also busy with his examinations. You can work on another issue in the meantime.
> 
> Hey, Thanks for it.You are absolutely correct. Apart from it I have GSOC tasks as well.

I understood, Good luck for GSOC
