### ISSUE TITLE
Auto Commenting when an issue is closed by repo maintainer

### ISSUE THREAD

**Issue by Asymtode712** [Akshat111111/Hedging-of-Financial-Derivatives#158]
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

**Comment by Asymtode712** [comment]
@Akshat111111 please assign me this issue under gssoc'24

**Comment by Akshat111111** [comment]
> This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

nice idea, you can start working on it.

**Comment by Asymtode712** [comment]
@Akshat111111 Please don't revert it, the error is occuring because GITHUB_TOKEN does not have necessary conditions to carry out the actions specified in the workflow file. The solution for this is:

1. Create a Personal Access Token (PAT)

- Go to your GitHub settings.
- Navigate to Developer settings -> Personal access tokens -> Tokens (classic).
- Generate a new token with the required scopes ( permission to be granted: repo).

2. Add the PAT to Your Repository Secrets

- Go to your GitHub repository.
- Navigate to Settings -> Secrets and variables -> Actions.
- Click New repository secret.
- Name it something like PAT_GITHUB and paste your PAT.

3. Update Your Workflow File

- Replace the instances of GITHUB_TOKEN with PAT_GITHUB

**Comment by Akshat111111** [comment]
> @Akshat111111 Please don't revert it, the error is occuring because GITHUB_TOKEN does not have necessary conditions to carry out the actions specified in the workflow file. The solution for this is:
> 
> 1. Create a Personal Access Token (PAT)
> 
> * Go to your GitHub settings.
> * Navigate to Developer settings -> Personal access tokens -> Tokens (classic).
> * Generate a new token with the required scopes ( permission to be granted: repo).
> 
> 2. Add the PAT to Your Repository Secrets
> 
> * Go to your GitHub repository.
> * Navigate to Settings -> Secrets and variables -> Actions.
> * Click New repository secret.
> * Name it something like PAT_GITHUB and paste your PAT.
> 
> 3. Update Your Workflow File
> 
> * Replace the instances of GITHUB_TOKEN with PAT_GITHUB

But it can cause future problems and its not necessary to do so

**Comment by Asymtode712** [comment]
@Akshat111111 ok no problem
