### ISSUE TITLE
Netflix movies trend analysis

### ISSUE THREAD

**Issue by Amarta113** [Akshat111111/Hedging-of-Financial-Derivatives#179]
Explore the Netflix dataset to understand the distribution of movies vs. TV shows, identify the countries producing the most content, and analyze the trend of releases over the years. What genres are most common, and how does the rating distribution vary across genres?

Analyse dataset
Handle null values
Data visualization to analyze:

- Top rating of movies
- Top rating tv shows
- Trend of release over the year
- Top countries with most content
- Identify and distribute most common genres

**Comment by Amarta113** [comment]
@Akshat111111 Assign me this issue I have done this

**Comment by itssiddhantjain** [comment]
Hello @Akshat111111 , please assign this issue to me as I have already worked on this kind of problem in past.

**Comment by Akshat111111** [comment]
Tell me your approach ??Dont forget to analyze the netflix stock too.

**Comment by itssiddhantjain** [comment]
@Akshat111111 I am planning to do it as I have done in a recommendation system in which I have used multiple recommender systems to analyze which will provide me the trending movies.

**Comment by Akshat111111** [comment]
> Can you assign me this problem @Akshat111111 . I wanna fix this issue.

whats your approach ??

**Comment by aryanchauh** [comment]
> > Can you assign me this problem @Akshat111111 . I wanna fix this issue.
> 
> whats your approach ??

Data Collection
Data Cleaning and Preprocessing: Clean the data by handling missing values, duplicates, and inconsistencies. 

Exploratory Data Analysis (EDA): Conduct EDA to understand the distribution of movie genres, ratings, release dates, etc
Sentiment Analysis:
Time Series Analysis: Explore time series data to identify seasonal trends, spikes in viewership, or shifts in popularity over time.
 Machine Learning Models 

Collaborative Filtering: Implement collaborative filtering techniques to recommend movies based on user
