### ISSUE TITLE
Loan Status Prediction Model

### ISSUE THREAD

**Issue by Seersha9802** [Akshat111111/Hedging-of-Financial-Derivatives#183]
**Is your feature request related to a problem? Please describe.**
Explore a dataset with parameters like the date of loan taken, credits etc.  and Predict whether the loan would be approved or not.

**Describe the solution you'd like**
I would like to use support vector Machine to make this predictive system.

**Describe alternatives you've considered**
It can further be transformed to a deep learning model which can fetch the fluctuations and accordingly draw conclusions.

**Additional context**

**Comment by Seersha9802** [comment]
@Akshat111111 Please assign this project to me under gssoc'24 tag.

**Comment by AyushSinghRajput1366** [comment]
I want to add a project that tells if your loan will be approved or not given your personal details. It has a website also which allows user to input their details and get predictions.

**Comment by AyushSinghRajput1366** [comment]
@Akshat111111 kindly assign me for this project as GSSOC'24

**Comment by AyushSinghRajput1366** [comment]
I have already made a project on this..

**Comment by Srijansarkar17** [comment]
Hey @Akshat111111 you can assign me this issue as i have worked on similar projects.

**Comment by Akshat111111** [comment]
> Hey @Akshat111111 you can assign me this issue as i have worked on similar projects.

Tell me your approach??It should not be same as the pr merged

**Comment by Srijansarkar17** [comment]
> > Hey @Akshat111111 you can assign me this issue as i have worked on similar projects.
> 
> Tell me your approach??It should not be same as the pr merged

I will try two ways for this project:
-> Neural Network
-> Simple Machine Learning Methods(but using Cross Validation)

The way which will give more accuracy will be chosen

**Comment by Srijansarkar17** [comment]
Hey @Akshat111111 I have pulled a PR. Can you please check it?
