### ISSUE TITLE
Add indicators, optimize hyperparameters, normalize data of RL Model.

### ISSUE THREAD

**Issue by FreeSpirit11** [Akshat111111/Hedging-of-Financial-Derivatives#193]
I want to make changes to "Hedging-of-Financial-Derivatives/RL Model /RL Trading.ipynb". I would add technical indicators using the `ta` library, utilize Optuna for hyperparameter optimization, and normalize data by filling missing values.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I have raised this issue. Please assign it to me.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , While attempting to add new features to the existing codebase, I encountered numerous issues and errors within the current implementation. Therefore, I recommend closing this issue until the existing codebase can be reviewed and resolved.

**Comment by Akshat111111** [comment]
Let others to work on it.
