### ISSUE TITLE
🪲[Bug]: Issue in autocommenting merged pr:

### ISSUE THREAD

**Issue by Anshika14528** [Akshat111111/Hedging-of-Financial-Derivatives#197]
**Describe the bug**
I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message
<img width="1442" alt="Screenshot 2024-05-27 at 3 41 34 PM" src="https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/168436423/626acd1c-c1d2-413e-836a-3a3dadc14e55">

**Additional context**
For the fix can you make sure you have these permissions on
<img width="675" alt="Screenshot 2024-05-27 at 3 03 30 PM" src="https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/168436423/e50e4b96-1dc2-4a85-aaab-fd763e5be6ef">
and if it doesn't work please let me work on this

**Comment by Akshat111111** [comment]
yes, you can work on it.
