### ISSUE TITLE
ARIMA implementation 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#20]
ARIMA (Autoregressive Integrated Moving Average) is a common time series forecasting technique, which is also used to hedge financial derivatives. The ARIMA model predicts future values of a time series based on past values. It's especially valuable for hedging since it can forecast future price fluctuations of a financial derivative, which can then be used to change the derivative's position to hedge against prospective losses.

You may use the following methods to create an ARIMA model for hedging financial derivatives:

1)Data Preparation: First, collect historical data for the financial derivative in question. Each trading day's opening, high, low, and closing prices should be included in this data.
2)Identify Parameters of the model: ARIMA models are defined.

3)Each trading day's opening, high, low, and closing prices should be included in this data.
Determine Model Parameters: Three parameters define ARIMA models: p (the order of the autoregressive portion), d (the order of differencing), and q (the order of the moving average part). You must determine appropriate values for these parameters. This is often accomplished via the use of approaches such as the Akaike Information Criterion (AIC) or the Bayesian Information Criterion (BIC). In some circumstances, a grid search or a random search may be used to determine the optimal settings. 

4. Fit the Model: Once the parameters have been determined, you may apply the ARIMA model to your data. This entails determining the coefficients for the autoregressive and moving average components of the equation.
Forecast Future Prices: Once the model has been fitted, you can use it to forecast future prices of financial derivatives. This is accomplished by employing the model's equations to determine anticipated prices based on previous prices.
develop a Hedging Strategy: You may develop a hedging strategy based on expected future pricing. For instance, if the forecasted price is expected to rise, you may purchase the derivative to profit from the rise. If the forecasted price falls, you may want to sell the derivative to reduce your losses.

**Comment by misskiran** [comment]
I can also help in this .May I?

**Comment by Akshat111111** [comment]
Yeah sure. I have assigned you this issue.

**Comment by apooyadv** [comment]
I think you should also add the case of random walk to this,it would be really insightful. If you allow me I'm willing to help you with this.

**Comment by Akshat111111** [comment]
I have already assigned this issue to @misskiran So you can create a separate issue of it

**Comment by apooyadv** [comment]
Okay

**Comment by diptarup794** [comment]
I want to work on this  for GSSOC'24.Kindly assign it to me @Akshat111111 . I have worked on Time Series before and would be able to implement it .

**Comment by Akshat111111** [comment]
This issue has been already assigned.If you have any specific idea, feel free to share
