### ISSUE TITLE
Hedged Cryptocurrencies 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#21]
Hedging in cryptocurrency works on the same principles as hedging in traditional financial markets. It entails investing in a linked asset that is predicted to move in the opposite way as the principal asset.

**Comment by apooyadv** [comment]
What exactly do we have to do here?

**Comment by Akshat111111** [comment]
> What exactly do we have to do here?

you can make a detailed study of movement of different currencies and the global financial markets like nifty, dow jones and other

**Comment by apooyadv** [comment]
Ok, I'll do it. Assign this to me.

**Comment by apooyadv** [comment]
What else do I need to do here?

**Comment by Akshat111111** [comment]
Its done.
