### ISSUE TITLE
Evaluation metrices RMSE, MSE and MAE

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#22]
Root Mean Square Error (RMSE), Mean Square Error (MSE) and Mean absolute Error (MAE) are a standard way to measure the error of a model in predicting quantitative data.

**Comment by AgrawalTitiksha** [comment]
Can you please describe a little more, about what is needed to be done for this issue.

**Comment by Akshat111111** [comment]
You have to build a ML model and then evaluate that model on various parameters.

**Comment by apooyadv** [comment]
Assign me this, I'll add these metrics to everywhere it is required.

**Comment by diptarup794** [comment]
I would like to work on this issue. Kindly assign it to me @Akshat111111

**Comment by Akshat111111** [comment]
@apooyadv is currently working on it.If he fails to do so,I will assign you

**Comment by varsha-ky12** [comment]
@Akshat111111 I would be glad to work on this ,when assigned to me.

**Comment by Akshat111111** [comment]
@varsha-ky12 you can work on some another issues @apooyadv is already working on it

**Comment by SwarnenduJUIT** [comment]
HI @Akshat111111 . I want to contribute . Kindly assign me this issue.

**Comment by MJakash** [comment]
Hey ! I wanna work on this issue if required. You can assign me this issue.

**Comment by Jashwanth05** [comment]
i think the task is to use all these parameters like rmse,mse,.... using ml. I think i am capable of doing this so please assign me,

**Comment by Akshat111111** [comment]
> HI @Akshat111111 . I want to contribute . Kindly assign me this issue.

Let see the work of  @apooyadv till the time  you can work on other issues.
