### ISSUE TITLE
💡[FEATURE]: implement two ensemble methods: a Voting Classifier and a Stacking Classifier on Loan Status Prediction Model.

### ISSUE THREAD

**Issue by FreeSpirit11** [Akshat111111/Hedging-of-Financial-Derivatives#220]
I want to implement two ensemble methods: a Voting Classifier and a Stacking Classifier on Loan Status Prediction Model (Loan Status Prediction/Loan_Status_prediction.ipynb):

For the Voting Classifier, I'll combine predictions from Logistic Regression, Support Vector Machine, and Random Forest classifiers.

For the Stacking Classifier, I'll use Logistic Regression as the meta-classifier on top of predictions from Logistic Regression, Support Vector Machine, and Random Forest classifiers.

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111, I have raised this issue. Please assign it to me.

**Comment by Akshat111111** [comment]
Very Good idea!

**Comment by binguliki** [comment]
Hey @Akshat111111 , The 4 Issues that have been raised recently are included in a issue that i have been working on issue number #203 Please check the issue and maintaining a fair chance of competition for everyone . I hope you understand my efforts and close the issues

**Comment by FreeSpirit11** [comment]
Hi @binguliki, I would suggest that you also keep working on your issue and let me also work on mine. My changes are small but your issue has lots of features in it. I have been working hard to understand the Loan Status Prediction Model and enhance it. I have completed working on most of my issues already. So @Akshat111111 can merge my changes and then your bigger changes can be merged too. I hope you understand. This way both of our efforts will not go in vain.

**Comment by binguliki** [comment]
@FreeSpirit11 but you cant raise same issue and work on it as it wont sensible.

**Comment by Akshat111111** [comment]
@binguliki your work is more advanced and you can keep working on it.I ensure you that anyone will not be replaced with your work
