### ISSUE TITLE
💡[FEATURE]: Web application For a Project

### ISSUE THREAD

**Issue by binguliki** [Akshat111111/Hedging-of-Financial-Derivatives#232]
**Is your feature request related to a problem? Please describe.**
I would love to add a `web application` for the House Price Prediction Project that was built earlier .

**Describe the solution you'd like**
I would be using flask as backend and manage different data pipelines that were used for data preprocessing
I would also provide a good front end which will be user-friendly

**Additional context**
@Akshat111111 Hey bro 👋 , Can you please assign this issue to me with level tag under GSSoC'24 so that i can work on it.

**Comment by Akshat111111** [comment]
Good idea, You can proceed further.

**Comment by binguliki** [comment]
@Akshat111111 , Thank you I'll be responding with a PR soon
