### ISSUE TITLE
💡[FEATURE]: NIFY DATA ANALYSIS(PREDICTION OF CLOSE PRICE USING NEURAL NETWORKS)

### ISSUE THREAD

**Issue by Srijansarkar17** [Akshat111111/Hedging-of-Financial-Derivatives#234]
**Is your feature request related to a problem? Please describe.**
There is no close price predictor of NIFTY. People invest their money in the wrong way by not being able to predict the current close price.

**Describe the solution you'd like**
I would develop a neural network that  would predict the close price of NIFTY.

**Describe alternatives you've considered**
-The feature would include proper data analysis of NIFTY
- Prediction of close price using the NIFTY dataset

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Akshat111111** [comment]
> I am interested in this issue. Please assign me this

Hey, create a new issue as per your idea

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model task.
