### ISSUE TITLE
💡[FEATURE]: Improve the Credit Risk Prediction project using Neural Networks

### ISSUE THREAD

**Issue by Srijansarkar17** [Akshat111111/Hedging-of-Financial-Derivatives#235]
**Is your feature request related to a problem? Please describe.**
The Credit Risk Prediction model does not have enough accuracy

**Describe the solution you'd like**
The Credit Risk Prediction model accuracy can be improved by using neural networks.

**Describe alternatives you've considered**
- Clear data visualization of the dataset
- Improve in accuracy by using neural networks

**Comment by Srijansarkar17** [comment]
Hey @Akshat111111 can you assign me this issue so that I can start working on it?

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this
