### ISSUE TITLE
💡[FEATURE]:  Add Visulizations For the Real Estate prediction project

### ISSUE THREAD

**Issue by binguliki** [Akshat111111/Hedging-of-Financial-Derivatives#238]
**Is your feature request related to a problem? Please describe.**
When i was earlier working over the web application project i was not able to quite understand the outcomes of the model that was used and i feel the results were not properly found

**Describe the solution you'd like**
I would be adding visulizations and for the results and also for the data set so that  a user can understand better about it . I would calculate the performance .

**Additional context**
@Akshat111111 Hey bro👋 , Can you please assign me the issue under GSSoC'24 with appropriate level tag

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Akshat111111** [comment]
> I am interested in this issue. Please assign me this

1 person is enough for this work, Kindly create a new issue as per your idea.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model task.

**Comment by Akshat111111** [comment]
> > I am interested in this issue. Please assign me this
> 
> 1 person is enough for this work, Kindly create a new issue as per your idea.

.
