### ISSUE TITLE
💡[FEATURE]: Model Enhancement using ensemble techniques

### ISSUE THREAD

**Issue by binguliki** [Akshat111111/Hedging-of-Financial-Derivatives#239]
**Is your feature request related to a problem? Please describe.**
The Real Estate prediction project doesn't perform well over the data , So I would like to add some more machine learning learning techniques.

**Describe the solution you'd like**
I would be using Stacking , Gradient Boosting , Ada Boost algorithms to improve the existing Model performance to support the existing web application.

**Additional context**
@Akshat111111 , Can you please assign me this under GSSoC'24 with an appropriate level tag so that i can work over it

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this
