### ISSUE TITLE
💡[FEATURE]:  Neural Networks for enhancing the model

### ISSUE THREAD

**Issue by binguliki** [Akshat111111/Hedging-of-Financial-Derivatives#240]
**Is your feature request related to a problem? Please describe.**
The Real estate project can be improvised using Neural Networks as they learn patterns and features very well

**Describe the solution you'd like**
I would be using a custom neural network and perform hyperparameter tuning for getting the best results. I would also provide visualizations for the Model performance.

**Additional context**
@Akshat111111 Hey Bro👋 , Can you assign me this issue under GSSoC'24 with appropriate level tag So that i can work upon it.

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Akshat111111** [comment]
> I am interested in this issue. Please assign me this

with your specific idea, you can create a new issue
