### ISSUE TITLE
💡[FEATURE]: Stock Market Prediction (Deep Learning Algorithms-neural networks with fine tuning and advanced optimization methods)

### ISSUE THREAD

**Issue by ranamanish674zu** [Akshat111111/Hedging-of-Financial-Derivatives#249]
Can you assign it to me? @Akshat111111 

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
Approach for this project: Will use Deep Learning algorithm and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by Shouryabhardwajj** [comment]
I want to complete this issue 
@Akshat111111  Please assign me this issue
