### ISSUE TITLE
Implementing using Reinforcement Learning

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#25]
Using reinforcement learning to implement hedging entails developing a trading environment in which the  (the learner) makes decisions based on market observations. The purpose is to maximize profit while minimizing loss (negative profit).

**Comment by adi271001** [comment]
please assign this to me under kwoc @Akshat111111

**Comment by Akshat111111** [comment]
Done, Thankyou for contribution.
