### ISSUE TITLE
💡[FEATURE]: Bank Loan modelling

### ISSUE THREAD

**Issue by PRIYANSHU2026** [Akshat111111/Hedging-of-Financial-Derivatives#260]
**Context**

This case is about a bank (Thera Bank) which has a growing customer base. Majority of these customers are liability customers (depositors) with varying size of deposits. The number of customers who are also borrowers (asset customers) is quite small, and the bank is interested in expanding this base rapidly to bring in more loan business and in the process, earn more through the interest on loans. In particular, the management wants to explore ways of converting its liability customers to personal loan customers (while retaining them as depositors). A campaign that the bank ran last year for liability customers showed a healthy conversion rate of over 9% success. This has encouraged the retail marketing department to devise campaigns to better target marketing to increase the success ratio with a minimal budget.

The department wants to build a model that will help them identify the potential customers who have a higher probability of purchasing the loan. This will increase the success ratio while at the same time reduce the cost of the campaign.

**Content**

Column descriptions ID Customer ID Age Customer's age in completed years Experience #years of professional experience Income Annual income of the customer ($000) ZIPCode Home Address ZIP code. Family Family size of the customer CCAvg Avg. spending on credit cards per month ($000) Education Education Level. 1: Undergrad; 2: Graduate; 3: Advanced/Professional Mortgage Value of house mortgage if any. ($000) Personal Loan Did this customer accept the personal loan offered in the last campaign? Securities Account Does the customer have a securities account with the bank? CD Account Does the customer have a certificate of deposit (CD) account with the bank? Online Does the customer use internet banking facilities? CreditCard Does the customer uses a credit card issued by UniversalBank?

Acknowledgements

This data set was given as part of course in machine learning. I have also added my observations on the data. I thank my faculty for giving an opportunity to work on this dataset.

Inspiration

Study the data distribution in each attribute, share your findings.
Use a classification model to predict the likelihood of a liability
customer buying personal loans.

**Comment by aryanchauh** [comment]
Hello @Akshat111111  can you assign me this issue . I wanna solve this issue

**Comment by Akshat111111** [comment]
> Hello @Akshat111111 can you assign me this issue . I wanna solve this issue

let @PRIYANSHU2026 solve this issue.You can create a new issue as per your specification.
