### ISSUE TITLE
💡[FEATURE]: Visualizations for Beta-weighted-stock-portfolio .

### ISSUE THREAD

**Issue by FreeSpirit11** [Akshat111111/Hedging-of-Financial-Derivatives#261]
Visualizations for Portfolio Analysis

**Description:**
- **Objective:** Enhance portfolio analysis by incorporating visualizations.
- **Summary:** The current portfolio analysis lacks visual insights, which can be crucial for decision-making. I aim to address this by adding visualizations using Matplotlib.
- **Visualizations:**
  1. **Portfolio Value by Stock:**
     - Bar chart showing the value of each stock in the portfolio.
     - X-axis: Stock names.
     - Y-axis: Value of each stock.

  2. **ASX200 Weighted Delta (point) by Stock:**
     - Bar chart showing the ASX200 weighted delta (point) for each stock in the portfolio.
     - X-axis: Stock names.
     - Y-axis: Delta (points).

  3. **ASX200 Weighted Delta (1%) by Stock:**
     - Bar chart showing the ASX200 weighted delta (1%) for each stock in the portfolio.
     - X-axis: Stock names.
     - Y-axis: Delta (1%).

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 ,I have raised this issue. Please assign it to me.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i have prior experience with the model task.
