### ISSUE TITLE
💡[FEATURE]: Bank Customer Segmentation: KMeans, HAC & DBScan

### ISSUE THREAD

**Issue by PRIYANSHU2026** [Akshat111111/Hedging-of-Financial-Derivatives#262]
**Context**

Financial institutions have diverse customers with different background, income levels etc. In order to formulate an effective marketing strategy, the financial institution would need to identify different segments of its customer portfolio and have a targeted approach to its customers based on their profile. This analysis would focus on clustering the financial institutions customers for the purposes of developing an optimum marketing strategy. The performance of the models will be evaluated based on its ability to clearly define the different customer segments in the dataset.

**Comment by adityasingh-0803** [comment]
this issue is interesting as data will collected having demographic information,financial levels etc. i can work on it is the language restricted to python or can we use R in it?

**Comment by Akshat111111** [comment]
> this issue is interesting as data will collected having demographic information, financial levels etc. I can work on it .Is the language restricted to python or can we use R in it?

yeah, you can use R.But dont forget to create a new folder in the directory named R Implementation

**Comment by adityasingh-0803** [comment]
how to add pull request? I have created the repository

**Comment by adityasingh-0803** [comment]
@Akshat111111 please look into as I have generated PR
