### ISSUE TITLE
Sentimental Analysis in Hedging 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#27]
Its all about the behavior of hedged market based on sentimental analysis

**Comment by adi271001** [comment]
can you please assign this to me under kwoc

**Comment by Akshat111111** [comment]
Sure I have assigned you this issue.You can start working on it

**Comment by Akshat111111** [comment]
Hey are you working on it ??

**Comment by adi271001** [comment]
Yes I was actually hospitalized for sometime should be done by this weekend

**Comment by adi271001** [comment]
@Akshat111111 can you give some context on the dataset , basically like price drop or like text

**Comment by Akshat111111** [comment]
> Yes I was actually hospitalized for sometime should be done by this weekend

Oh, Take care.Health is the first priority

**Comment by adi271001** [comment]
i have raised a pull request please merge it under swoc

**Comment by Akshat111111** [comment]
Thanks for contributing. I have merged the PR.
