### ISSUE TITLE
💡[FEATURE]: Movie Recommendation System

### ISSUE THREAD

**Issue by Srijansarkar17** [Akshat111111/Hedging-of-Financial-Derivatives#271]
**Is your feature request related to a problem? Please describe.**
This repository does not contain recommendation system projects

**Describe the solution you'd like**
I will create a movie recommendation system which will recommend five movies to the user based on the search of the user just like netflix. The model will be created using Cosine Similarity Algorithm of machine learning .

**Comment by Akshat111111** [comment]
If you can build stock recommendation system then I can assign you this

**Comment by Akshat111111** [comment]
This repo is financial repo not ml based repo.

**Comment by aryanchauh** [comment]
> If you can build stock recommendation system then I can assign you this

No sir I haven't built that . And I got it

**Comment by Srijansarkar17** [comment]
I will create a new issue for it
