### ISSUE TITLE
💡[FEATURE]: implement codeql ci/cd workflow for `python`

### ISSUE THREAD

**Issue by harmeetsingh11** [Akshat111111/Hedging-of-Financial-Derivatives#272]
### Description

The repository contains code in `python` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] I am to work on this issue
- [X] I am gssoc'24 contributor

**Comment by binguliki** [comment]
@Akshat111111 , I would also like to work on this issue can you please assign this task to me

**Comment by Akshat111111** [comment]
> @Akshat111111 , I would also like to work on this issue can you please assign this task to me

@harmeetsingh11 is already working on it.So let him firstly raise a pr then you can improve it
