### ISSUE TITLE
💡[FEATURE]: Credit Card Fraud Detection using Neural Networks

### ISSUE THREAD

**Issue by Srijansarkar17** [Akshat111111/Hedging-of-Financial-Derivatives#275]
**Is your feature request related to a problem? Please describe.**
Frauds of credit cards nowadays are going unnoticed. That is why a credit card fraud detection system is built

**Describe the solution you'd like**
I will build a credit card fraud detection system that can detect credit card frauds and it will be trained using neural networks. I will also add data visualization to the model for better understanding.

**Comment by Srijansarkar17** [comment]
Hey @Akshat111111 I would like you assign me this issue

**Comment by binguliki** [comment]
Hey @Akshat111111  , I would also like to work on this issue . Can you please assign this issue to me
