### ISSUE TITLE
 Flight Fare Prediction

### ISSUE THREAD

**Issue by Pranshu-jais** [Akshat111111/Hedging-of-Financial-Derivatives#276]
Aim : Building Flask web app which predicts fare of Flight ticket.

Approach : preprocessing dataset ,performing EDA and building model using using ml algorithm like RandomForestRegressor,XG boost etc trained on relevant features and deploying the model using flask web app.

Please assign this project to me as part of GSSoC'24 with the gssoc label and the appropriate level (1/2/3)
Expectation level : 3

**Comment by Akshat111111** [comment]
Make a new folder as Python Web apps and put your folder over there.
