### ISSUE TITLE
💡[FEATURE]: Historical Stock Market Dataset Analysis

### ISSUE THREAD

**Issue by ranamanish674zu** [Akshat111111/Hedging-of-Financial-Derivatives#290]
This dataset includes the historical daily prices and volume information for US stocks and ETFs trading on NASDAQ, NYSE, and NYSE MKT. The data was last updated on November 10th, 2017 and the files are all in CSV format.
https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs
Can you assign it to me? @Akshat111111

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
Approach for this project: Will use Deep Learning algorithm and python & some optimization algorithms
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by Akshat111111** [comment]
This work is already done
