### ISSUE TITLE
Implementing the same thing with different markets, indices or stocks 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#3]
The same code can be implemented with different stocks exchange of the world or different pairs of stocks

**Comment by Akshat111111** [comment]
> Hi! I would be interested in implementing the same code with the NY stock exchange. I can get started on trying to implement that

Yeah That's good, You can start implementing  it using NY stock exchange.If you have any queries,Please feel free to ask

**Comment by michaelfred533** [comment]
I implemented your code with banking stocks in the New York Stock Exchange. I just created a separate jupyter notebook for the NYSE stocks. I can submit a pull request to add the new notebook
Your project is really interesting! I was thinking it would be fun to test it out with some different sector stocks too and maybe play around with the trade signal threshold too.

**Comment by Akshat111111** [comment]
That's good, Please submit the pull request of it by creating a new folder of NYSE, and I will merge it. Talking about this project, It also fascinating for me.Yeah, your idea to test it out with some different sector stocks too is also a good idea to work on .Thanks again for working on this project. If you have any queries, please feel free to ask.
