### ISSUE TITLE
Hedging using KNN

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#30]
KNN is a fundamental machine learning approach that works with a database of categorized data. It may be used to categorize each form of investment in a database into high, moderate, and low profit potential groups.

**Comment by misskiran** [comment]
Can I help you with this??

**Comment by Akshat111111** [comment]
> Can I help you with this??

Yeah.Can you please elaborate your idea

**Comment by Divyanshi1002** [comment]
Hello,
I would like to contribute for this issue by collecting historical data, 
websites: https://finance.yahoo.com/quote/%5ENSEI/history/
https://cafim.sssup.it/~giulio/other/alpha_vantage/
https://www.google.com/finance/?hl=en
I will preprocess the collected historical data, including cleaning, handling missing values, and scaling numerical features if needed. Then, I will train a KNN model using the preprocessed data to categorize investments into the specified profit potential groups
Looking forward to contributing to this project!

Best regards,
Divyanshi
GSSOC'24 contributor

**Comment by apooyadv** [comment]
I have already made a model with KNN before. I'm also thinking of making a model with DBSCAN and compare the results of both.

**Comment by Akshat111111** [comment]
> Hello, I would like to contribute for this issue by collecting historical data, websites: https://finance.yahoo.com/quote/%5ENSEI/history/ https://cafim.sssup.it/~giulio/other/alpha_vantage/ https://www.google.com/finance/?hl=en I will preprocess the collected historical data, including cleaning, handling missing values, and scaling numerical features if needed. Then, I will train a KNN model using the preprocessed data to categorize investments into the specified profit potential groups Looking forward to contributing to this project!
> 
> Best regards, Divyanshi GSSOC'24 contributor

Yes you can move forward

**Comment by Akshat111111** [comment]
> I have already made a model with KNN before. I'm also thinking of making a model with DBSCAN and compare the results of both.

You can make a new issue specifically mentioning DBSCAN

**Comment by diptarup794** [comment]
I want to work on this for GSSOC'24. Kindly assign it to me @Akshat111111

**Comment by Akshat111111** [comment]
@Divyanshi1002 is already working on it

**Comment by Divyanshi1002** [comment]
Hi @Akshat111111 ,

Thank you for assigning me this issue. I'm using a KNN model to predict the daily return, with the Open, Close, High, and Low prices as features.

I'm encountering some errors in the code. Could you please clarify the deadline for completing this task?

**Comment by Akshat111111** [comment]
> Hi @Akshat111111 ,
> 
> Thank you for assigning me this issue. I'm using a KNN model to predict the daily return, with the Open, Close, High, and Low prices as features.
> 
> I'm encountering some errors in the code. Could you please clarify the deadline for completing this task?

There is no such deadline,you can move at your own speed.Refer official documentation to avoid errors

**Comment by SwarnenduJUIT** [comment]
hi @Akshat111111 . I am a student currently exploring and applying various ml algorithms. I want to contribute . kindly assign me this issue
