### ISSUE TITLE
Building Risk Assesment Model 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#31]
This risk assesment model can use any machine learning algorithm to estimate past,current and future risk of the model.

**Comment by apooyadv** [comment]
You can assign me this. I've previous made a credit risk assessment model, I'll borrow some ideas from it. You can also check out the credit risk repo on my acc.

**Comment by Akshat111111** [comment]
Its about estimation of the maximum risk of the strategy

**Comment by apooyadv** [comment]
Okay, cool. I'll work on it, if you allow me to.

**Comment by Akshat111111** [comment]
Yes you can take the incharge.

**Comment by apooyadv** [comment]
Thank you!

**Comment by MJakash** [comment]
i wanna work on this issue

**Comment by Akshat111111** [comment]
@apooyadv is already working on it,you can work on any other existing issues
