### ISSUE TITLE
💡[FEATURE]: Walmart stock Price Prediction Using LSTM, SGD And Random Forest

### ISSUE THREAD

**Issue by vivekvardhan2810** [Akshat111111/Hedging-of-Financial-Derivatives#331]
**Is your feature request related to a problem? Please describe.**

Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

**Describe the solution you'd like**

I Aim to  develop a machine learning model using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, predicting the Stock Price, Analyzing the High and low stocks over a period of time.

**Describe alternatives you've considered**
For this Solution I would like to Add the ML Models which i am gonna build like using  LSTM, RNN, Random Forest, and SGD (Stochastic Gradient Derivative).

**Additional context**

_No response_

**Comment by vivekvardhan2810** [comment]
@Akshat111111, Please Assign me this Issue GSSOC'24 label and the appropriate level, as i have done the projects based on stock prices.

**Comment by Akshat111111** [comment]
There is a lot already done with the  netflix stock, so kindly change the title and do walmart stock analysis

**Comment by vivekvardhan2810** [comment]
Okay @Akshat111111, will change and do it.

**Comment by Akshat111111** [comment]
And put your walmart stock analysis folder inside NYSE

**Comment by vivekvardhan2810** [comment]
Okay, @Akshat111111

Sir, can i use the kaggle dataset

**Comment by Akshat111111** [comment]
yes, but dont forget to add it in reference
