### ISSUE TITLE
Job Fraud Detection

### ISSUE THREAD

**Issue by SayantikaLaskar** [Akshat111111/Hedging-of-Financial-Derivatives#332]
Objective : This model would predict whether a job is fraudulent or not based on various features.

This model would understand data, preprocess, train logistic regression; assess metrics, interpret coefficients.

**Comment by Akshat111111** [comment]
> Objective : This model would predict whether a job is fraudulent or not based on various features.
> 
> This model would understand data, preprocess, train logistic regression; assess metrics, interpret coefficients.

Do some implementation related to finance
