### ISSUE TITLE
💡[FEATURE]: Airline Customer Satisfaction using Neural Networks

### ISSUE THREAD

**Issue by Srijansarkar17** [Akshat111111/Hedging-of-Financial-Derivatives#340]
**Is your feature request related to a problem? Please describe.**
Airlines nowadays are confused about whether their customers are satisfied or not. For this problem, I would like to build an airline customer satisfaction prediction model.

**Describe the solution you'd like**
This model will be built using Neural Networks for great accuracy. It will predict whether a customer is satisfied or not with the airline based on various features like delay timings, cleanliness etc. This model will also contain data visualization.

**Comment by Srijansarkar17** [comment]
@Akshat111111 Can you please assign me this issue? I would like to work on it.

**Comment by adityasingh-0803** [comment]
interesting issue
please assign me 
I would like to work on it

**Comment by Akshat111111** [comment]
Its going out of the domain, focus on financial analysis
