### ISSUE TITLE
💡[FEATURE]: Enhance Customer Churn Prediction Model

### ISSUE THREAD

**Issue by 4ryn** [Akshat111111/Hedging-of-Financial-Derivatives#342]
**Is your feature request related to a problem? Please describe.**
Yes, enhance the model .
**Describe the solution you'd like**
1. I want to apply LSTM network to the model  
2. Add the Readme file

**Comment by adityasingh-0803** [comment]
a basic framework for building and evaluating a logistic regression model for churn prediction

**Comment by adityasingh-0803** [comment]
using confuse matrix we can do the churn

**Comment by Akshat111111** [comment]
Its going out of the domain, focus more on financial analysis
