### ISSUE TITLE
💡[FEATURE]: Apple stock Price Prediction Using LSTM, SVR, Decision Tree Regressor And Random Forest

### ISSUE THREAD

**Issue by vivekvardhan2810** [Akshat111111/Hedging-of-Financial-Derivatives#344]
**Is your feature request related to a problem? Please describe.**
Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

**Describe the solution you'd like**
I would like to Add the ML Models which i am gonna build like using LSTM, SVR, Random Forest, and Decision tree Regressor using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy. 

**Describe alternatives you've considered**
Exploring additional models like ARIMA, XGBoost, or ensemble methods for potential improvement in forecasting accuracy.

**Additional context**

**Comment by vivekvardhan2810** [comment]
@Akshat111111 Sir, under which folder do I have to add this project.

**Comment by Akshat111111** [comment]
> @Akshat111111 Sir, under which folder do I have to add this project.

NYSE, put your folder.

**Comment by Akshat111111** [comment]
Your folder name- Apple Stock Analysis
