### ISSUE TITLE
💡[FEATURE]: Sentiment Analysis Using Groq API

### ISSUE THREAD

**Issue by Amarta113** [Akshat111111/Hedging-of-Financial-Derivatives#380]
**Is your feature request related to a problem? Please describe.**
To analysis the sentiment faster I used LPU based API.

**Describe the solution you'd like**
I used Groq API. The Groq LPU's helps to reduce the amount of time per word calculated, enabling faster text sequence generation.

**Comment by Akshat111111** [comment]
It should be related to financial domain
