### ISSUE TITLE
Tesla Historic Stock Price Analysis using GRU and BiGRU

### ISSUE THREAD

**Issue by abckhush** [Akshat111111/Hedging-of-Financial-Derivatives#381]
**Is your feature request related to a problem? Please describe.**
I would like to analyze Tesla's stock performance with a comprehensive dataset that provides a detailed record of daily stock prices from Kaggle.

**Describe the solution you'd like**
I would like to analyze the stock prices using GRU and BiGRU.

**Comment by Akshat111111** [comment]
Kindly specify the stocks name, they should be unique

**Comment by Akshat111111** [comment]
I mean the work should be unique

**Comment by abckhush** [comment]
https://www.kaggle.com/datasets/muhammadibrahimqasmi/tesla-stock-insights-and-predictions/data
is this ok?

**Comment by Akshat111111** [comment]
The work should be your own, not anyone else

**Comment by abckhush** [comment]
It is my own work. Yes, I have taken help, but it is not an exact copy.

**Comment by Akshat111111** [comment]
sure
