### ISSUE TITLE
Building an web app 

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#39]
It can be implemented using any framework of python or javascript.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Shivani-Sharma-23** [comment]
Hi ! Please assign this task to me . I had already on frameworks for creating web apps. Please assign !

**Comment by Akshat111111** [comment]
Done

**Comment by Akshat111111** [comment]
Which framework you are using ??

**Comment by Akshat111111** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

Which framework ??

**Comment by Shivani-Sharma-23** [comment]
i can create a python web app using streamlit and if you want a version with css styling then taipy would be fine

**Comment by Akshat111111** [comment]
> i can create a python web app using streamlit and if you want a version with css styling then taipy would be fine

Sure you can move forward

**Comment by Akshat111111** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

Can you implement the same thing in javascript?? You can use react or any other thing

**Comment by IP80808080** [comment]
Yes, i was going to use react.js

**Comment by Akshat111111** [comment]
Sure you can do it

**Comment by Tarun2605** [comment]
I am also interested in this task please assign me.

**Comment by Akshat111111** [comment]
> I am also interested in this task please assign me.

2 peoples are already working on it with different technologies.Which framework you wants to work on ??

**Comment by SPraveenKumar-spk** [comment]
Hi admin, I would like to work up on this using Flask python framework. can you please assign this to me under gssoc24

**Comment by Akshat111111** [comment]
> Hi admin, I would like to work up on this using Flask python framework. can you please assign this to me under gssoc24

yes you can implement it

**Comment by Akshat111111** [comment]
Any update ?? @SPraveenKumar-spk @IP80808080 @Shivani-Sharma-23

**Comment by SPraveenKumar-spk** [comment]
Hi admin   @Akshat111111  work in progress. I will complete it

**Comment by Shivani-Sharma-23** [comment]
Almost done with Implementation. Will Update you soon about completion @Akshat111111

**Comment by Akshat111111** [comment]
Yeah, no worries
