### ISSUE TITLE
Data analysis on financial instruments

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#4]
undertake web research,data collection and data analysis on it

**Comment by Akshat111111** [comment]
> I also might be able to help out with this. What kind of research/analysis are you looking for?

I am looking for Automated Trading, But I'm also open to new ideas regarding it.

**Comment by bhartijoshi04** [comment]
Hello !
I am quite skilled in data analysis and performing research. I would like to contribute to this project.
Looking forward to it

**Comment by apooyadv** [comment]
Assign me this. I'll make a separate model for automated trading. You can also check our my repos,they give an idea of my work.

**Comment by Akshat111111** [comment]
> Hello ! I am quite skilled in data analysis and performing research. I would like to contribute to this project. Looking forward to it

Sure you can start working on it

**Comment by Akshat111111** [comment]
> You can assign this to me. I'll make a separate model for automated trading. You can also check our my repos,they give an idea of my work.

I can know your interest,but lets give @bhartijoshi04 a chance and you can then enhance this further.

**Comment by apooyadv** [comment]
Okay :) @Akshat111111

**Comment by bhartijoshi04** [comment]
> > You can assign this to me. I'll make a separate model for automated trading. You can also check our my repos,they give an idea of my work.
> 
> I can know your interest,but lets give @bhartijoshi04 a chance and you can then enhance this further.

Thank you for giving me the chance sir, I'll do my best
