### ISSUE TITLE
💡[FEATURE]: Predicting COVID-19 from Chest X-Ray Images

### ISSUE THREAD

**Issue by ashis2004** [Akshat111111/Hedging-of-Financial-Derivatives#406]
**Is your feature request related to a problem? Please describe.**
The prediction of COVID-19 from chest X-ray images using Convolutional Neural Networks (CNNs) has several critical use cases in the healthcare sector. Firstly, it enhances diagnostic accuracy and speed in clinical settings, especially in regions with limited access to PCR testing facilities. By rapidly analyzing X-ray images, CNNs can assist radiologists in identifying COVID-19-related abnormalities, enabling timely isolation and treatment of infected individuals. Secondly, CNN-based models can serve as valuable tools in emergency departments, where quick decision-making is essential. They help in triaging patients, determining the severity of lung involvement, and prioritizing those needing immediate medical attention.

**Describe the solution you'd like**
Built and trained a convolutional neural network in Keras with TensorFlow as backend from scratch to predict patients if they were infected with COVID-19 or not using their chest X-ray images. Matplotlib was used for data visualization. Data preprocessing and data augmentation was carried out using tensorflow 2.0 The model used was sequential with a combination of convolutional layers, pooling layers, dropout layers, dense layers with relu activation and output layer with sigmoid activation. The dataset contained the lungs X-ray images of both groups i.e non-covid and covid infected patients. The dataset was obtained from kaggle. Metrics chosen for model evaluation were Training set, test set and validation set accuracy. Adam optimizer with learning rate of 0.001 was choosed for gradient descent The entire project was carried out on the Google Colab environment Results of the model were following:

Training Set Accuracy : 98.41 %

Training Set Loss : 0.0490

Validation Set Accuracy : 97.51 %

Validation Set Loss: 0.0759

Test Set Accuracy : 94.83 %

Test Set Loss : 0.1141

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/110098153/cbeba7b2-2edd-48c1-afca-95020cfd869a)
![image](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/110098153/4606170a-2b04-496c-ac5a-8735a0b75d38)

**Comment by ashis2004** [comment]
@Akshat111111 please assign it to me

**Comment by Akshat111111** [comment]
this is a  financial repo
