### ISSUE TITLE
💡[FEATURE]: Credit score classification using Machine Learning

### ISSUE THREAD

**Issue by RajKhanke** [Akshat111111/Hedging-of-Financial-Derivatives#411]
**Is your feature request related to a problem? Please describe.**

This project aims to classify the credit score of the personality as high, medium, low based on various input features like age, occupation, income, homeownership, assets, dependents, liabilities etc.

It will help to identify the pattern and trends which affects the credit score of a customer

**Describe the solution you'd like**
I will train the machine learning model on given Kaggle dataset :
https://www.kaggle.com/datasets/eneskosar19/credit-score-classification-clean-data

i will also do a complete data analysis and EDA, comparison between various algorithms and write my all setup and work under readme.md

**Describe alternatives you've considered**
on an alternative i can also predict the credit score (regression  method) if found relevant data.

**Additional context**
none

**Comment by Akshat111111** [comment]
You need to make a app for it and based on the parameters it will give the prediction
