### ISSUE TITLE
💡[FEATURE]:  Salary prediction using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [Akshat111111/Hedging-of-Financial-Derivatives#413]
**Is your feature request related to a problem? Please describe.**

Salary , Revenue and taxes are important part of Indian financial system. Salary prediction project predicts the salary of an individual based on various inputs like age, gender , occupation ,  Job Title, Year of Experience , Salary etc.

It will also give an idea of which factors affect the salary of individuals based on their education level and job.

**Describe the solution you'd like**
I will train the machine learning model from the below dataset :-
https://www.kaggle.com/datasets/rkiattisak/salaly-prediction-for-beginer/data

I will compare the strength of models like linear regression ,random forest etc , do a complete data analysis and perform EDA. I wll also prepare readme.md file.

**Additional context**
None

**Comment by vishalmaurya850** [comment]
Assign me this project under GSSOC 24

**Comment by Akshat111111** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Salary , Revenue and taxes are important part of Indian financial system. Salary prediction project predicts the salary of an individual based on various inputs like age, gender , occupation , Job Title, Year of Experience , Salary etc.
> 
> It will also give an idea of which factors affect the salary of individuals based on their education level and job.
> 
> **Describe the solution you'd like** I will train the machine learning model from the below dataset :- https://www.kaggle.com/datasets/rkiattisak/salaly-prediction-for-beginer/data
> 
> I will compare the strength of models like linear regression ,random forest etc , do a complete data analysis and perform EDA. I wll also prepare readme.md file.
> 
> **Additional context** None

kindly make a prediction app similar to data scrapper for it

**Comment by Akshat111111** [comment]
And this folder will be named as Human resource analysis

**Comment by Akshat111111** [comment]
> Assign me this project under GSSOC 24

you can create another issue with your idea

**Comment by vishalmaurya850** [comment]
ok
