### ISSUE TITLE
💡[FEATURE]: End to End bank customer churn prediciton 

### ISSUE THREAD

**Issue by vishuhere** [Akshat111111/Hedging-of-Financial-Derivatives#426]
**Is your feature request related to a problem? Please describe.**
Bank managers and customer service teams are often frustrated by their inability to accurately predict customer churn and intervene in a timely manner to retain valuable clients. High customer churn rates in the banking industry lead to significant revenue loss and increased costs for acquiring new customers. Retaining customers is crucial for long-term profitability, but identifying which customers are likely to churn and understanding the reasons behind their decisions can be challenging.

**Describe the solution you'd like**
Develop an end-to-end machine learning solution to predict customer churn in the banking industry and integrating it with Streamlit to make a complete web-app.

**Describe alternatives you've considered**
Rule-Based Systems: A rule-based system that uses predefined business rules to identify churn risks. However, this lacks the adaptability and accuracy of machine learning models.

Third-Party Solutions: Using third-party customer relationship management (CRM) systems with built-in churn prediction. While convenient, these may not be tailored to the specific needs and data of the bank.

**Comment by Khushi-Pushkar** [comment]
Hey @Akshat111111 . Can u please assign this issue to me

**Comment by Akshat111111** [comment]
@vishuhere have you worked on it??

**Comment by Khushi-Pushkar** [comment]
Hey @Akshat111111 . Can u please assign this issue to me
