### ISSUE TITLE
Random Walk in python.

### ISSUE THREAD

**Issue by apooyadv** [Akshat111111/Hedging-of-Financial-Derivatives#43]
Random Walks are are the limiting case of Auto Regressive One.

**Comment by KushalTrivedi19032005** [comment]
I'm a beginner in Machine Learning & Open Source having good theoretical knowledge on MLDL and practically having worked on supervised and unsupervised learning. Do you think I can contribute to this project @apooyadv ? If yes, I would be happy to learn and contribute!

**Comment by Akshat111111** [comment]
> I'm a beginner in Machine Learning & Open Source having good theoretical knowledge on MLDL and practically having worked on supervised and unsupervised learning. Do you think I can contribute to this project @Akshat111111 ? If yes, I would be happy to learn and contribute!

Yeah you can contribute.I will suggest you to start with the basic issues and then move to more advanced
