### ISSUE TITLE
💡[FEATURE]:  Swiggy stock price using Predictive Modelling .

### ISSUE THREAD

**Issue by Shantnu-singh** [Akshat111111/Hedging-of-Financial-Derivatives#459]
# Description
Combine multiple machine learning models (e.g., decision trees, neural networks, SVMs) to improve the accuracy and robustness of Predictive modelling.
# Objectives
Develop various models to predict Stock prices.
Test the model on historical data.
Compare its performance with individual models.

Can you assign it to me? @Akshat111111

**Comment by Akshat111111** [comment]
this stock not exists
