### ISSUE TITLE
we can use ANN or logistic regression 

### ISSUE THREAD

**Issue by PRIYANSHU2026** [Akshat111111/Hedging-of-Financial-Derivatives#46]
for better accuracy and better result we can use these two algorithms especially for financial prediction

**Comment by keshavk21** [comment]
Hi !!
Can you assign me this issue?

**Comment by PRIYANSHU2026** [comment]
> Hi !! Can you assign me this issue?

hey already I have made

**Comment by Akshat111111** [comment]
> for better accuracy and better result we can use these two algorithms especially for financial prediction

yes we can use it

**Comment by utsabsamadder** [comment]
Hey is there a possibility for me to Join here? I have a specialty in Deep Learning and Neural Networks to be specific. I can surely help with ANN or Logistic Regression.

Thanks and Have my Best Regards.

**Comment by Akshat111111** [comment]
> Hey is there a possibility for me to Join here? I have a specialty in Deep Learning and Neural Networks to be specific. I can surely help with ANN or Logistic Regression.
> 
> Thanks and Have my Best Regards.

I will suggest you to create a new issue with specific functionality.
