### ISSUE TITLE
Hedging using DBSCAN

### ISSUE THREAD

**Issue by apooyadv** [Akshat111111/Hedging-of-Financial-Derivatives#47]
Build a model using DBSCAN and compare it with the model built with KNN.

**Comment by SanjanaBankar** [comment]
Hello, @apooyadv 

I have previous experience with DBSCAN algorithm which I used in my project on "image forgery detection" for detecting copy-move forgery in images and relative experience in KNN. I will try my best to work on this issue.

Please assign me this under GSSOC'24, and in the assignees

Looking forward to contributing to this project!

Regards,
Sanjana

**Comment by apooyadv** [comment]
I've already started working on it. Also, I'm not the project admin.

**Comment by SanjanaBankar** [comment]
> I've already started working on it. Also, I'm not the project admin.

Alright!

**Comment by apooyadv** [comment]
You can surely enhance it later.

**Comment by tejasvinigoel** [comment]
Could you pls assign this issue to me, thanks

**Comment by Akshat111111** [comment]
> Could you pls assign this issue to me, thanks

@apooyadv is already working on it,you can create a new issue by implementing any special feature of DBSCAN
