### ISSUE TITLE
💡[FEATURE]: Diamond Price prediction using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [Akshat111111/Hedging-of-Financial-Derivatives#481]
**Is your feature request related to a problem? Please describe.**

Assets are important aspects of financial derivatives and one of them are diamonds. This project aims to predict the estimated price of diamonds in market using machine learning and regression techniques by taking different inputs from user -:
1)diamond weight in carats
2) diamond's shape in x, y and z axis
3)diamond's color and cutting quality
4)depth
5)width of widest point and sharpness etc.

**Describe the solution you'd like**
i will train machine learning models on following data :
https://www.kaggle.com/datasets/amirhosseinmirzaie/diamonds-price-dataset
i will do complete data Science procedures including analysis ,EDA , feature engineering and processing and deployed the trained model with the help of application (GUI) using Streamlit package in python.

**Additional context**
None

**Comment by Akshat111111** [comment]
make a web app of it

**Comment by RajKhanke** [comment]
okay , please look forward towards my PR of salary prediction
