### ISSUE TITLE
💡[FEATURE]: Credit Risk Model & Scorecard

### ISSUE THREAD

**Issue by abckhush** [Akshat111111/Hedging-of-Financial-Derivatives#484]
**Is your feature request related to a problem? Please describe.**
Developing a reliable and accurate credit risk model is essential for financial institutions to predict the probability of default (PD) and assign credit scores to borrowers.

**Describe the solution you'd like**
The solution is to develop a data-driven credit risk model in Python that predicts the probabilities of default (PD) and assigns credit scores to existing or potential borrowers. The model should utilize a highly interpretable and easy-to-implement scorecard, allowing for straightforward calculation of credit scores.

Dataset: https://www.kaggle.com/datasets/somyaagarwal69/loan-data-2015/data

**Comment by Akshat111111** [comment]
I similar work is already done, with a web app.So you have something unique ??

**Comment by abckhush** [comment]
In the Credit Risk folder that is present in the repo, only models have been trained. 
That can be further used to calculate the scorecards of the users and set the loan approval cutoffs to find the ideal threshold so that the acceptance rate of loans is high.

**Comment by abckhush** [comment]
@Akshat111111 can I use another dataset than what is present in the repo because it doesn't have necessary information for me to calculate the scorecards?
I'll upload in the same folder if you want but just different dataset.

**Comment by Akshat111111** [comment]
yes, do it
