### ISSUE TITLE
💡[FEATURE]: Predicting user churn

### ISSUE THREAD

**Issue by Aditi22Bansal** [Akshat111111/Hedging-of-Financial-Derivatives#488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly assign me this issue

**Comment by Akshat111111** [comment]
this is also completed
