### ISSUE TITLE
Add Bank Customer Churn Prediction Model

### ISSUE THREAD

**Issue by ananyag309** [Akshat111111/Hedging-of-Financial-Derivatives#493]
Customer churn refers to the phenomenon where customers stop doing business with a company. In the context of a bank, it means customers closing their accounts or ceasing to use banking services. Build a model using Python and popular machine learning libraries such as scikit-learn. It will incorporates classification algorithms including Logistic Regression, Random Forest, Decision Tree, Gradient Boosting, and AdaBoost.

please assign this issue to me under gssoc

**Comment by Akshat111111** [comment]
done already
