### ISSUE TITLE
Value of risk calculation(Var)

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#5]
VaR is a measure of the risk of investment loss. It calculates how much a group of assets would lose (with a specified probability) in a specific time period, such as a day, under typical market conditions.

**Comment by apooyadv** [comment]
You can assign me this. I will demonstrate the three commonly used VaRs wherever they're needed.

**Comment by tejasvinigoel** [comment]
Could you please assign this to me, thanks

**Comment by Akshat111111** [comment]
> Could you please assign this to me, thanks

you can work on risk management at nifty 50

**Comment by tejasvinigoel** [comment]
ive raised a merge request, kindly accept, thanks

**Comment by tejasvinigoel** [comment]
I've made the changes, kindly check again and let me know if further changes are required. I'm not able to view the graphs on github which are visible on google colab/ jupyter so ive made a separate folder for the same

**Comment by Akshat111111** [comment]
> I've made the changes, kindly check again and let me know if further changes are required. I'm not able to view the graphs on github which are visible on google colab/ jupyter so ive made a separate folder for the same

Making the separate folder is great idea.
