### ISSUE TITLE
Typo Error in README File

### ISSUE THREAD

**Issue by Amarta113** [Akshat111111/Hedging-of-Financial-Derivatives#50]
I noticed a minor typo error in the README file of the project.
There is spelling mistake in README file about the code of conduct link.

![type error](https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/134733248/b8973137-1a87-415f-8521-93977c914d91)

**Comment by Amarta113** [comment]
@Akshat111111 Assign me this issue I can resolve this.

**Comment by Akshat111111** [comment]
Okay correct it
