### ISSUE TITLE
📝[Docs]: Update the readme file

### ISSUE THREAD

**Issue by vedi9969** [Akshat111111/Hedging-of-Financial-Derivatives#529]
I would like to update the readme file by adding setup and installation process like how they can clone the project, how to make PR in project and so  on many such things so the contributors can know how to do it. It will help many other who visits the project.  Below I've attached the image please refer it.
![2](https://github.com/user-attachments/assets/c413ea0f-9fae-4329-bd11-3db193e15538)

**Comment by Akshat111111** [comment]
Only add the above thing, and dont disturb the content of current readme

**Comment by vedi9969** [comment]
yess
