### ISSUE TITLE
💡[FEATURE]:  Restaurant Revenue prediction using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [Akshat111111/Hedging-of-Financial-Derivatives#550]
**Is your feature request related to a problem? Please describe.**
yes, it is related to the financial sector for predicting the revenue and making analysis of factors that affect the revenue of the restaurant.

**Describe the solution you'd like**
i will predict the Restaurant revenue from the various input fields like cuisine , location , rating, seating capacity meal price range, marketing or advertisement done or not , social media followers , avg customer visited  using machine learning techniques and display output using a Streamlit based web application with proper analysis ,prediction EDA , feature engineering. i will try multiple ml models as well.

dataset link : https://www.kaggle.com/datasets/anthonytherrien/restaurant-revenue-prediction-dataset

**Comment by RajKhanke** [comment]
@Akshat111111  please assign this issue to me along with level and label of gssoc'24.

**Comment by Akshat111111** [comment]
dont forget to add the hotel chain stock with it too

**Comment by RajKhanke** [comment]
okay ,please look forwards towards my pr as well, and i will make a web for it as well

**Comment by Akshat111111** [comment]
sure
