### ISSUE TITLE
Crude Oil Analysis

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#59]
It  involves data analysis and prediction of crude oil

**Comment by Amarta113** [comment]
@Akshat111111 Assign me this issue I will work on it.

**Comment by apooyadv** [comment]
Assign this to me, I'm interested in working on this.

**Comment by amishhaa** [comment]
Can i work on this ? My approach is to build a Random Forest crude oil price prediction model.

**Comment by palayushi293** [comment]
hello ,, pls assign this issue to me i will give my best
Waiting for your response

**Comment by tejasvinigoel** [comment]
Im interested in this, kindly assign it to me

**Comment by Satyam0775** [comment]
I would like to work on this issue. Please assign this task to me

**Comment by Akshat111111** [comment]
> It involves data analysis and prediction of crude oil under the main folder- Hedging by crude oil

**Comment by Akshat111111** [comment]
@apooyadv  @tejasvinigoel lets give others some task, you can then improve upon.

**Comment by Akshat111111** [comment]
@amishhaa has done the work,are you also working with new feature?? @Amarta113

**Comment by Akshat111111** [comment]
> @Akshat111111 Yes I am working on it, the dataset is too large therefore I am delay

If you are facing any issue in uploading the dataset, convert it to zip file.

**Comment by Amarta113** [comment]
> 

Yet its not ready to upload,  I need some time to complete it. Is it necessary to upload now?

**Comment by Akshat111111** [comment]
yes it is needed.

**Comment by diptarup794** [comment]
@Akshat111111 I am interested in working on this issue . Kindly assign it to me if possible

**Comment by Akshat111111** [comment]
One implementation is already there, so create a new issue with a specific functionality.
