### ISSUE TITLE
Building a basic python library

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#60]
You can refer to this https://www.reddit.com/r/learnpython/comments/13ouob6/how_to_create_a_python_packagelibrary/?rdt=50001  for more clarity

**Comment by tejasvinigoel** [comment]
What’s the library expected to do?

**Comment by apooyadv** [comment]
A library about what?

**Comment by Akshat111111** [comment]
The library should be about quantitative finance methodology

**Comment by apooyadv** [comment]
Ok, I wanna work on this. Please assign this to me.

**Comment by akshaydubey05** [comment]
Hi, i would like to solve this issue, Could you please assign this issue to me? 
Also, please specify which functions should be applied .

Thanks
