### ISSUE TITLE
OCR implementation of financial documents

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#61]
The Optical character recognition or optical character reader (OCR) is the conversion of images of typed, handwritten or printed text into machine-encoded text, from a scanned documents

**Comment by tejasvinigoel** [comment]
Im interested, kindly assign it to me

**Comment by tejasvinigoel** [comment]
kindly check merge request

**Comment by Akshat111111** [comment]
Yeah

**Comment by diptarup794** [comment]
Hi @Akshat111111 . I want to work on this issue .Kindly assign it to me if possible

**Comment by Dhwanika26** [comment]
Hello, @Akshat111111 Kindly assign this Task to me. I am interested in working on this problem.

**Comment by diptarup794** [comment]
@Akshat111111  Should I continue working on this ?

**Comment by Akshat111111** [comment]
> @Akshat111111 Should I continue working on this ?

If your work is unique, keep working on it and create a new issue
