### ISSUE TITLE
💡[FEATURE]: Landing Club Loan Analysis 

### ISSUE THREAD

**Issue by ananyag309** [Akshat111111/Hedging-of-Financial-Derivatives#635]
The goal is to create a Machine Learning Model which will Analyse or predict Landing Club Loan with an accuracy of 79%

Dataset
The dataset is collected from the following link,https://www.kaggle.com/datasets/wordsforthewise/lending-club

**Comment by ananyag309** [comment]
@Akshat111111 sir please let me know in which folder to add this

**Comment by Akshat111111** [comment]
loan folder
