### ISSUE TITLE
Building a cryptography algo for securing AI model

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#64]
You are free to use any algo like DES,AES or other

**Comment by apooyadv** [comment]
Can you provide more description?

**Comment by Akshat111111** [comment]
You can add some authentication protocols or any security algorithm so that a particular key will be required to access the model.

**Comment by karanmanglani** [comment]
I would like to work on this issue. I have previously worked on cryptography as can be seen from 
https://github.com/karanmanglani/MyPythonCode/tree/main/Project%20Applications/Cryptographer

**Comment by Akshat111111** [comment]
Yeah, I have seen your work.You can start working on it.

**Comment by karanmanglani** [comment]
Is the key a single key valid for all users or it should be based on user information like name and email etc and each user would have different key valid only for that particular user?

**Comment by aryan1165** [comment]
Hello, @Akshat111111 I have opened a PR addressing this issue. Can you please look into it?

**Comment by Akshat111111** [comment]
sure

**Comment by Akshat111111** [comment]
@karanmanglani you can create a new issue  as per your specification and then create a pull request.
