### ISSUE TITLE
enhancement of SK-learn models

### ISSUE THREAD

**Issue by PRIYANSHU2026** [Akshat111111/Hedging-of-Financial-Derivatives#69]
we can use hyperparamete method to get good accuracy and give better result and also use logistic regression especialy for binary digits and also apply ROC method to increase accuracy 

there are other method like pipeline but it may not suitable for financial datasets.

give your openions

**Comment by Akshat111111** [comment]
> we can use hyperparamete method to get good accuracy and give better result and also use logistic regression especialy for binary digits and also apply ROC method to increase accuracy
> 
> there are other method like pipeline but it may not suitable for financial datasets.
> 
> give your openions

yes you can go forward with it.

**Comment by PRIYANSHU2026** [comment]
Ok sir I will enhance on the project from this repository with good accuracy

**Comment by Akshat111111** [comment]
sure.
