### ISSUE TITLE
Incorporating backtesting library

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#8]
Backtesting is a Python module for backtesting trading strategies against historical data. It is compatible with a wide range of financial products, including forex, cryptocurrency, stocks, and futures. For best usage, the library is built on top of ecosystem libraries such as Pandas, NumPy, and Bokeh.

**Comment by mdutta1234** [comment]
How many years of historical data would you like me to use for the backtest?

**Comment by mdutta1234** [comment]
When I kept the start date as 2018-12-02 and end date as 2022-12-01(yyyy-mm-dd format), the CAGR is very less compared to NIFTY Bank and the Portfolio Performance is lower than Benchmark for most part of the Portfolio Performance vs Benchmark graph.

**Comment by Akshat111111** [comment]
Thanks for considering this repository for contribution,The duration should be last 3-4 years.

**Comment by Akshat111111** [comment]
You can try considering different sectors,which can give better results as compared to bank nifty

**Comment by mdutta1234** [comment]
Ok thank you, I will check the performance for other sectors

**Comment by mdutta1234** [comment]
Hello, I checked out the performance of the other sectors and found the cagr was lesser in the case of the trading algorithm w.r.t the benchmark, although when I looked at the graph against the benchmark I found that CAGR of trading algo should be higher.So I wanted to crosscheck the CAGR calculation function .Please check the function below which I modified:

def calculate_cagr_b(portfolio):

  final_portfolio = portfolio['total'].iloc[-1]
  initial_portfolio = portfolio['total'].iloc[0]
  delta = len(portfolio.index)
  print('Number of trading days = ', delta)
  YEAR_DAYS = 252*4
  returns = (final_portfolio/initial_portfolio) ** (YEAR_DAYS/delta) - 1
  return returns

I changed Year_days to 252*4 as I was checking for last 4 years , is this correct?

**Comment by Akshat111111** [comment]
Yeah, you can proceed further.After implementing it raise a PR so that I can review it.Talking about the performance, we will raise an another issue for its optimization.

**Comment by mdutta1234** [comment]
Ok thanks a lot.

**Comment by Akshat111111** [comment]
I am assigning this issue to you,so that you can add the PR
