### ISSUE TITLE
Adding Mathematical methods for quantitative finance

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#80]
You can add math models which helps in financial forcasting.

**Comment by sreesti07** [comment]
Could you assign this to me? I'm interested.

**Comment by aryan1165** [comment]
Can you provide me some clarity on types of models, Can SVMs or Bayesian networks be considered as mathematical models? Also Can you assign this issue to me. Thanks

**Comment by Janvibaghel** [comment]
hello @Akshat111111  I'm interested in this issue and I want to work on it . Kindly please assign this issue to me .

**Comment by Akshat111111** [comment]
> Can you provide me some clarity on types of models, Can SVMs or Bayesian networks be considered as mathematical models? Also Can you assign this issue to me. Thanks

No

**Comment by Akshat111111** [comment]
I have assigned this issue.Kindly tell which amthematical model you will add ??

**Comment by sreesti07** [comment]
machine learning techniques such as neural networks and deep learning, advanced stochastic calculus methods, numerical methods for solving partial differential equations (PDEs). Can be added ?

**Comment by Akshat111111** [comment]
yes can be added.Do it by creating a new mathematical modelling folder.

**Comment by sreesti07** [comment]
Yes will start by adding a folder

**Comment by diptarup794** [comment]
I want to work on this issue . Kindly assign it to me

**Comment by Akshat111111** [comment]
There is already a lot of people working here.
