### ISSUE TITLE
💡[FEATURE]: Pharmaceutical-Products-Sales-Forcasting

### ISSUE THREAD

**Issue by Aditijainnn** [Akshat111111/Hedging-of-Financial-Derivatives#808]
A ml project

**Comment by Akshat111111** [comment]
you can predict pharma stocks

**Comment by Aditijainnn** [comment]
will predict the sales volume in units of 5 pharmaceutical products for 4 months including Covid-19 period. The work fulfilled the best prediction scores in a competition with MAPE scores ranging from 3% to 11% for 4 products.
