### ISSUE TITLE
💡[FEATURE]: Impact of Macroeconomic Indicators on Stock Market Volatility

### ISSUE THREAD

**Issue by Aditi22Bansal** [Akshat111111/Hedging-of-Financial-Derivatives#822]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
This analysis will explore how various macroeconomic indicators, such as GDP growth, inflation rates, and unemployment rates, influence stock market volatility. I will use historical data on macroeconomic indicators and stock market indices to perform the analysis.
**Describe alternatives you've considered**

**Additional context**

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly assign me this issue

**Comment by Aditi22Bansal** [comment]
@Akshat111111
Kindly assign me this issue

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Is this already done?

**Comment by Akshat111111** [comment]
the pr which is merged can be seen in the PR section
