### ISSUE TITLE
Monte carlo simulation in hedging

### ISSUE THREAD

**Issue by Akshat111111** [Akshat111111/Hedging-of-Financial-Derivatives#9]
Monte Carlo simulation provides a straightforward approach for numerically pricing stocks; but, it does not immediately produce the weights required to form a replicating portfolio.

**Comment by mdutta1234** [comment]
I am interested in doing this, can you please assign me this?

**Comment by mdutta1234** [comment]
Hello ,can you please elaborate on what exactly we need to do in this issue?

**Comment by Akshat111111** [comment]
Hey, you can use Monte Carlo Simulation for Volatility Model or Monte Carlo Simulation for Investment Portfolio Growth by making a different folder for it.
Like the similar code.
`import numpy as np
from helpers import get_random_returns, get_confidence_levels, get_yearly_percentiles
from plots import plot_histogram, plot_yearly_percentiles

def perform_simulation(inputs):
   years = inputs['end_age'] - inputs['start_age']
   pot = inputs['starting_pot']
   returns = get_random_returns(years=years)
   mean_return = (np.mean(returns) - 1) * 100
   history = []
   for i in range(years):
       annual_return = returns[i]
       pot *= annual_return
       pot += inputs['annual_contributions']
       history.append(int(pot))
   return pot, history, mean_return

def perform_monte_carlo(inputs, n=1000):
   pot_sizes = []
   results = []
   mean_returns = []
   for i in range(n):
       final_amount, history, mean_return = perform_simulation(inputs)
       pot_sizes.append(final_amount)
       results.append(history)
       mean_returns.append(mean_return)
   lower_confidence, upper_confidence = get_confidence_levels(pot_sizes)
   return {
       'pot_sizes': pot_sizes,
       'results': results,
       'yearly_percentiles': get_yearly_percentiles(results, inputs),
       'lower_confidence': lower_confidence,
       'upper_confidence': upper_confidence,
       'mean_returns': mean_returns
   }

inputs = {
   'start_age': 20,
   'end_age': 65,
   'starting_pot': 5000,
   'annual_contributions': 500 * 12,
   'target_amount': 300000,
   'n_simulations': 10000
}

mc = perform_monte_carlo(inputs, n=inputs['n_simulations'])`

**Comment by Akshat111111** [comment]
U can consider different stocks and implement it similar like [https://www.kaggle.com/code/ianchute/house-prices-monte-carlo-inference](url) this code does for house price prediction.

**Comment by mdutta1234** [comment]
Ok, this sounds interesting, I would like to do this issue.

**Comment by Akshat111111** [comment]
Yeah, its very interesting and there is always new to explore in it .

**Comment by mdutta1234** [comment]
Hey, so I reviewed many resources on Monte Carlo simulation on stocks, I found mostly they are using Geometric brownian motion(GBM) , should I also implement a Monte carlo simulation using GBM?

**Comment by Akshat111111** [comment]
Yeah you can proceed with GBM implementation for it

**Comment by mdutta1234** [comment]
Hello, I have pulled request for the monte carlo simulation, please check if its good enough. Thanks.

**Comment by Akshat111111** [comment]
Hey, I have reviewed your pull request and Its really good. Thankyou for your time and contribution.
