### ISSUE TITLE
📝[Docs]:  add data_fetcher.py

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Akshat111111/Hedging-of-Financial-Derivatives#993]
**What Docs changes are you proposing?**
To handle live market data fetching from various APIs.

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
Functions to connect to data providers, fetch real-time data, and handle errors.

**Describe the solution you'd like**
Provide a clear and concise description of the changes you'd like to see implemented in the documentation.

**Describe alternatives you've considered**
If you've thought about alternative approaches or solutions, briefly describe them here.

**Additional context**
Add any additional context, examples, or screenshots related to the proposed documentation changes.

**Comment by AKSHITHA-CHILUKA** [comment]
add this file in risk assessment

**Comment by AKSHITHA-CHILUKA** [comment]
I can add all the changes through one pull request

**Comment by AKSHITHA-CHILUKA** [comment]
please assign me the issue

**Comment by Akshat111111** [comment]
add a issue and PR of 1 project, not individual files

**Comment by AKSHITHA-CHILUKA** [comment]
Yeah I will do that
