### ISSUE TITLE
📝[Docs]: add risk_calculator.py

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Akshat111111/Hedging-of-Financial-Derivatives#994]
**What Docs changes are you proposing?**
To calculate various risk metrics like VaR, CVaR, etc.

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
Functions to compute risk metrics based on the fetched market data.

**Describe the solution you'd like**
Provide a clear and concise description of the changes you'd like to see implemented in the documentation.

**Describe alternatives you've considered**
If you've thought about alternative approaches or solutions, briefly describe them here.

**Additional context**
Add any additional context, examples, or screenshots related to the proposed documentation changes.

**Comment by AKSHITHA-CHILUKA** [comment]
add this file in risk assessment

**Comment by Akshat111111** [comment]
add your entire folder inside risk management

**Comment by AKSHITHA-CHILUKA** [comment]
I will add all the file in one pull request
